version: '2'
services:
  web:
    build: .
    ports:
      - "8007:8765"
    env_file: .env
    volumes:
      - ./webapp:/opt/webapp
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
