# Generated by Django 3.1.6 on 2021-02-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210205_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_make',
            field=models.CharField(max_length=72),
        ),
        migrations.AlterField(
            model_name='cars',
            name='model_name',
            field=models.CharField(max_length=136),
        ),
    ]
