# Generated by Django 3.1.6 on 2021-02-05 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210205_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='make',
            field=models.CharField(max_length=72),
        ),
        migrations.CreateModel(
            name='CarRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.SmallIntegerField()),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='cars.carmodels')),
            ],
        ),
    ]
